name: crypto_wallet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  firebase_auth: ^4.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^5.1.5
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.7.0
  mrx_charts: ^0.1.3
  path_provider: ^2.0.11
  timeago: ^3.3.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  hive_generator: ^2.0.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/
